feat(requirements.txt): add
add toch==2.4.0 because

❯ python classify_text.py
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Traceback (most recent call last):
  File "/Users/lloyd/github/Complainers-R-Us-Org/Complainers-R-Us/Person 2: Dataset Processing & Text Classification (Stream 2)/classify_text.py", line 4, in <module>
    classifier = pipeline('text-classification')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lloyd/.pyenv/versions/3.12.4/lib/python3.12/site-packages/transformers/pipelines/__init__.py", line 895, in pipeline
    framework, model = infer_framework_load_model(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lloyd/.pyenv/versions/3.12.4/lib/python3.12/site-packages/transformers/pipelines/base.py", line 237, in infer_framework_load_model
    raise RuntimeError(
RuntimeError: At least one of TensorFlow 2.0 or PyTorch should be installed. To install TensorFlow 2.0, read the instructions at https://www.tensorflow.org/install/ To install PyTorch, read the instructions at https://pytorch.org/.
❯ python classify_text.py
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.
Traceback (most recent call last):
  File "/Users/lloyd/github/Complainers-R-Us-Org/Complainers-R-Us/Person 2: Dataset Processing & Text Classification (Stream 2)/classify_text.py", line 4, in <module>
    classifier = pipeline('text-classification')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lloyd/.pyenv/versions/3.12.4/lib/python3.12/site-packages/transformers/pipelines/__init__.py", line 895, in pipeline
    framework, model = infer_framework_load_model(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lloyd/.pyenv/versions/3.12.4/lib/python3.12/site-packages/transformers/pipelines/base.py", line 237, in infer_framework_load_model
    raise RuntimeError(
RuntimeError: At least one of TensorFlow 2.0 or PyTorch should be installed. To install TensorFlow 2.0, read the instructions at https://www.tensorflow.org/install/ To install PyTorch, read the instructions at https://pytorch.org/.