fix(page.js): fix typo
Failed to compile.
./app/page.js
37:12  Error: `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`.  react/no-unescaped-entities
info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
Error: Command "npm run build" exited with 1

❯ npm run build

> frontend-app@0.1.0 build
> next build

  ▲ Next.js 14.2.5
  - Environments: .env.local

   Creating an optimized production build ...
 ✓ Compiled successfully
 ✓ Linting and checking validity of types
 ✓ Collecting page data
 ✓ Generating static pages (6/6)
 ✓ Collecting build traces
 ✓ Finalizing page optimization

Route (app)                              Size     First Load JS
┌ ○ /                                    7.76 kB         130 kB
├ ○ /_not-found                          871 B          87.9 kB
└ ○ /complain                            31.6 kB         154 kB
+ First Load JS shared by all            87.1 kB
  ├ chunks/23-51a9e7ce1896f839.js        31.5 kB
  ├ chunks/fd9d1056-90960e0a7e77703c.js  53.6 kB
  └ other shared chunks (total)          1.9 kB

○  (Static)  prerendered as static content